quarkus.application.name=transaction-service
quarkus.http.port=8080

# ==============================================================================
# Kafka Broker & SmallRye Reactive Messaging
# ==============================================================================
# Usa la variable KAFKA_BOOTSTRAP_SERVERS si existe (K8s/Docker), sino localhost:9092
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Canal de salida hacia Kafka
mp.messaging.outgoing.transactions-out.connector=smallrye-kafka
mp.messaging.outgoing.transactions-out.topic=tx-received
mp.messaging.outgoing.transactions-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.transactions-out.acks=all

# Desactivar Dev Services si ya cuentas con un Kafka corriendo localmente
# quarkus.kafka.devservices.enabled=false
